variable:
  profiles : dev
spring:
  redis:
    host: 127.0.0.1  # IP
    port: 6379  # 端口号
    password: redis  # 密码
    timeout: 10000 # 连接超时时间（毫秒）
    database: 1 # Redis默认情况下有16个分片，这里配置具体使用的分片，默认是0
    pool:
      max-active: 200 # 连接池最大连接数
      max-wait: -1ms  # 连接池最大阻塞等待时间（使用负值表示没有限制）
      min-idle: 0 # 连接池中的最小空闲连接
      max-idle: 10 # 连接池中的最大空闲连接
